import type { NextPage } from "next"
import { useState, useEffect } from "react"
import { useRouter } from "next/router"
import Head from "next/head"
import Image from "next/image"
import styles from "../../styles/Home.module.css"
import { NewsEntity } from "../../core/entity"
import { NewsAPI } from "../../core/microcms"

const Post: NextPage = () => {
    const router = useRouter()
    const [news, setNews] = useState<NewsEntity.News | undefined>()

    useEffect(() => {
        if (router.asPath !== router.route) {
            const refresh = async () => {
                const news = await NewsAPI.getNewsById(
                    router.query.pid as string
                )
                setNews(news)
            }
            refresh()
        }
    }, [router])

    return (
        <div className={styles.container}>
            <Head>
                <title></title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>{news?.title}</h1>
                <p>{news?.text}</p>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default Post
