import type { NextPage } from "next"
import { useState, useEffect } from "react"
import Head from "next/head"
import Image from "next/image"
// import Link from "next/link"
import styles from "../../styles/Home.module.css"
import { NewsEntity } from "../../core/entity"
import { NewsAPI } from "../../core/microcms"
import { NewsCell } from "../../components/NewsCell"

const News: NextPage = () => {
    const [news, setNews] = useState<NewsEntity.News[]>([])
    const refresh = async () => {
        const news = await NewsAPI.listNews()
        setNews(news)
    }
    useEffect(() => {
        refresh()
    }, [])

    return (
        <div className={styles.container}>
            <Head>
                <title>News</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Welcome to news!</h1>

                <div className={styles.grid}>
                    {news.map((item, i) => {
                        return <NewsCell key={i} news={item} />
                    })}
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export default News
