import type { NextPage } from "next"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import News from "../components/News"

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                <h2 className={styles.title}>Welcome to CMS Templates!</h2>
                <News />
            </div>
        </div>
    )
}

export default Home
